print('type(123): %s' %type(123))
print("type('str'):%s" %type('str'))
print('type(None):%s' %type(None))
print('type(abs):%s' %type(abs))

print('type(123)==type(456)? ',end='')
print(type(123)==type(456))
print('type(123)==int? ',end='')
print(type(123)==int)
print("type('123')==type('abc')? ",end='')
print(type('123')==type('abc'))
print('type(abc)==str? ',end='')
print(type(123)==int)
print("type('abc')==type(123)? ",end='')
print(type('abc')==type(123))
